music/urls.py
from django.urls import path, re_path
from . import views

app_name = 'music'  # It's the name of the app diff app have diff name and for example if two or move have same url ass detail so how django will know which detail page to open name: detail have same in other apps too

urlpatterns = [
    # /music/
    path('', views.IndexView.as_view(), name='index'),
    
    # /music/
    re_path(r'^register/$', views.UserFormView.as_view(), name='register'),
    
    # /music/<album_id>/ adding re_path for regular expression
    re_path(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    
    # /music/<album_id>/favorite/
    #re_path(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
    
    #/music/album/add/
    re_path(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),
    
    #/music/album/2/
    re_path(r'album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),
    
    #/music/album/2/delete 
    re_path(r'album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.urlpatterns import format_suffix_patterns
from companies import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'music/', include('music.urls')),
    path('stock/', views.StockList.as_view()),
    
]

urlpatterns = format_suffix_patterns(urlpatterns)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

companies/models.py
from django.db import models

# Create your models here.

class Stock(models.Model):
    ticker = models.CharField(max_length=100)
    open = models.FloatField()
    close = models.FloatField()
    volume = models.FloatField()
    
    def __str__(self):
        return self.ticker
    

music/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Album(models.Model):
    artist = models.CharField(max_length=250)
    alum_title =models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    #alum_logo = models.CharField(max_length=1000)
    alum_logo = models.ImageField()
    
    def get_absolute_url(self):
        return reverse("music:detail", kwargs={"pk": self.pk})
    
    
    
    def __str__(self) :
        return self.alum_title + '-' + self.artist
    
class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)
    
    def __str__(self):
        return self.song_title
    
    

companies/views.py
from django.shortcuts import render
from .serializer import StockSerializer
from rest_framework.response import Response
# Create your views here.
from .models import Stock
from rest_framework.views import APIView

class StockList(APIView):
    
    def get(self, request):
        stock = Stock.objects.all()
        serializer = StockSerializer(stock, many=True)
        
        return Response(serializer.data)
        
    def post(self, request):
        pass

music/views.py
from django.views import generic
from .models import Album
from django.views.generic import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from .form import UserForm

class IndexView(generic.ListView):
    template_name = "music/index.html"
    context_object_name = 'object_list'

    def get_queryset(self):
        return Album.objects.all()
    

class DetailView(generic.DetailView):
    model =Album
    template_name = 'music/detail.html'
    
class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'alum_title', 'genre', 'alum_logo']
    
class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'alum_title', 'genre', 'alum_logo']

class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')

class UserFormView(View):
    form_class = UserForm
    template_name = 'music/registration_form.html'
    
    # display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form':form})
    
    # process form data 
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            
            user = form.save(commit=False)
            
            # cleaned (normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()
            
            # return User objects if credentials are correct
            user = authenticate(username=username, password=password)
        
            if user is not None:
            
                if user.is_active:
                    login(request, user)
                    return redirect('music:index')
            
        return render(request, self.template_name, {'form': form})















# from django.shortcuts import render, get_object_or_404
# from .models import Album, Song
# # from django.http import Http404

# def index(request):
#     all_album = Album.objects.all()
#     context = {
#         'all_album' : all_album,
#     }
#     return render(request, 'music/index.html', context )

# def detail(request, album_id):
#     # try:
#     #     album = Album.objects.get(pk = album_id)
#     # except Album.DoesNotExist:
#     #     raise Http404("Album Does not exist")
#     album = get_object_or_404(Album, pk=album_id)
#     return render(request, 'music/detail.html', {'album': album})

# def favorite(request, album_id):
#     album = get_object_or_404(Album, pk=album_id)
#     try:
#         selected_song = album.song_set.get(pk=request.POST['song'])
#     except(KeyError, Song.DoesNotExist):
#         return render(request, 'music/detail.html', {
#             'album': album,
#             'error_message': "You did not selected vaild song!!",
#             })
#     else:
#         selected_song.is_favorite = True
#         selected_song.save()
#         return render(request, 'music/detail.html', {'album': album})
    

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add a New Albums{% endblock  %}
{% block album_active %}active{% endblock  %}

{% block body  %}

<div class="container-fluid"> 

    <div class='row'>

        <div class='col-sm-12 col-md-7'>
            <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form-tamplate.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>

    </div>

</div>

{% endblock  %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Viberr{% endblock title %}</title>
    <!-- Load the path to your static files -->

    {% load static %}

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/feather-icons"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Satisfy">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-dark">
        <div class="container-fluid">
        <a class="navbar-brand"  href="{% url 'music:index' %}">Viberr</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a class='active' href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-cd"></span>&nbsp;<!--adding space by &nbsp--> Albums
                    </a>
                </li>
                <li>
                    <a href="#">
                        <span class="glyphicon glyphicon-music"></span>&nbsp;<!--adding space by &nbsp--> Songs
                    </a>
                </li>
                
        </ul>

        <form class="navbar-form navbar-left" role="search" method="get" action="#">
            <div class="form-group">
                <input class="form-control " type="text" placeholder="Search"  name="q" value="">
            </div>
            <button class="btn btn-default" type="submit">Search</button>
        </form>

        <ul class="nav navbar-nav navbar-right">
            <li class="">
                <a href="{% url 'music:album-add' %}">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                </a>
            </li>
            <li class="">
                <a href="#">
                    <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Log Out
                </a>
            </li>
        </ul>

      </div>
    </div>
  </nav> 
  {% block body %}{% endblock body %}
</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}Detail Page{% endblock title %}
{% block body %}

    <img src="{{ album.alum_logo.url }}">

    <h1>{{ album.alum_title }} </h1>
    <h3>{{album.artist }} </h3>
    {% for song in album.song_set.all  %}
    <label for="song{{forloop.counter}}">
        {{song.song_title}}
    </label><br>
{% endfor %}

    {% comment %} <ul>
        {% for song in album.song_set.all   %}
            <li>
                {{ song.song_title }} - {{ song.file_type }}
            </li> 
        {% endfor %}
    </ul> {% endcomment %}

    {% comment %} {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}

    <form action="{% url 'music:favorite' album.id %}" method="post">
        {% csrf_token %}
        {% for song in album.song_set.all  %}
            <input type="radio" id="song{{forloop.counter}}" name="song" value="{{song.id}}" />
            <label for="song{{forloop.counter}}">
                {{song.song_title}}
                {% if song.is_favorite %}
                    <img src='http://clipart-library.com/images/qTBAkEKzc.png'/>
                {% endif %}
            </label><br>
        {% endfor %}
        <input type='submit' value='Favorite'>
    </form> {% endcomment %}
{% endblock body %}

music/templates/music/form-tamplate.html
{% for field in form  %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span>{{ field.errors }}</span>
        </div> 
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{field }}</div>
    </div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}
{% block title %}Albums{% endblock title %}
{% block body %}
    {% if object_list %}
        <h3>Here are all my Albums<br/></h3>
        <ul>
            <li>
                {% for album in object_list %}
                <!--detail is the name or path removing hardcore url // music:detail-->
                <a href="{% url 'music:detail' album.id %}"> 
                    {{album.alum_title}}<br/>
                </a>
                {% endfor %}
            </li>
        </ul>
        {% else %}
        <h3>You don't have any Albums</h3>
        {% endif %}
{% endblock body %}

music/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block title %}Register User {% endblock  %}

{% block body  %}

<div class="container-fluid"> 

    <div class='row'>

        <div class='col-sm-12 col-md-7'>
            <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form-tamplate.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>

    </div>

</div>

{% endblock  %}